name: Docker Deploy CI    
    
on:    
  push:    
    branches: [ "master" ]    
    
jobs:    
    
  build:    
    runs-on: self-hosted    
        
    steps:    
    - uses: actions/checkout@v3    
    - name: Build the Dockerized server    
      run: |    
        echo "${{ secrets.ENV_FILE }}" > .env    
        docker-compose up --build -d